In [1]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [2]:
list(enumerate(alphabets))

[(0, 'A'),
 (1, 'B'),
 (2, 'C'),
 (3, 'D'),
 (4, 'E'),
 (5, 'F'),
 (6, 'G'),
 (7, 'H'),
 (8, 'I'),
 (9, 'J'),
 (10, 'K'),
 (11, 'L'),
 (12, 'M'),
 (13, 'N'),
 (14, 'O'),
 (15, 'P'),
 (16, 'Q'),
 (17, 'R'),
 (18, 'S'),
 (19, 'T'),
 (20, 'U'),
 (21, 'V'),
 (22, 'W'),
 (23, 'X'),
 (24, 'Y'),
 (25, 'Z')]

In [3]:
dict(list(enumerate(alphabets)))

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [4]:
int_to_char = dict(list(enumerate(alphabets)))

In [5]:
int_to_char[6]

'G'

In [6]:
for i, v in enumerate(alphabets):
    print(v,i)

A 0
B 1
C 2
D 3
E 4
F 5
G 6
H 7
I 8
J 9
K 10
L 11
M 12
N 13
O 14
P 15
Q 16
R 17
S 18
T 19
U 20
V 21
W 22
X 23
Y 24
Z 25


In [7]:
char_to_int = dict((v,i) for i, v in enumerate(alphabets))

In [8]:
char_to_int['X']

23

In [10]:
### Prepare the dataset
seq_length = 1
x = []
y = []

for i in range(len(alphabets)-seq_length):
    seq_in=alphabets[i]
    seq_out=alphabets[i+1]
    print(seq_in,'--->',seq_out)
    x+=[[char_to_int[seq_in[0]]]]
    y+=[char_to_int[seq_out]]

A ---> B
B ---> C
C ---> D
D ---> E
E ---> F
F ---> G
G ---> H
H ---> I
I ---> J
J ---> K
K ---> L
L ---> M
M ---> N
N ---> O
O ---> P
P ---> Q
Q ---> R
R ---> S
S ---> T
T ---> U
U ---> V
V ---> W
W ---> X
X ---> Y
Y ---> Z


In [11]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [12]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

In [13]:
import numpy as np
np.shape(x)


(25, 1)

In [14]:
x=np.reshape(x,(25,1,1)) #sample, time steps/sequence length, feature

In [15]:
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [16]:
x_norm=x/25 #Normalization range 0~25 --> 0.04~1 small scale, nearly same value good in optimization

In [17]:
x_norm

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

In [18]:
from tensorflow.keras.utils import to_categorical

In [19]:
a = [1,3,2,3,2,1,1,2,3]

In [20]:
to_categorical(a)

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
y_new=to_categorical(y)
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [22]:
from keras.layers import SimpleRNN, Dense, Input
from keras.models import Sequential

In [27]:
model = Sequential()

In [28]:
model.add(Input((1,1)))
model.add(Dense(25,activation='relu'))
model.add(SimpleRNN(32))
model.add(Dense(26,activation='softmax'))

In [29]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 1, 25)          │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 26)             │           858 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,764 (10.80 KB)

 Trainable params: 2,764 (10.80 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [31]:
model.fit(x_norm,y_new,epochs=500,batch_size=1)

Epoch 1/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: 3.2907    
Epoch 2/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0400 - loss: 3.2674     
Epoch 3/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0400 - loss: 3.2576     
Epoch 4/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 3.2475 
Epoch 5/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 3.2378 
Epoch 6/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: 3.2282 
Epoch 7/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0400 - loss: 3.2194 
Epoch 8/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0400 - loss: 3.2107 
Epoch 9/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0400 - loss: 3.1990     
Epoch 10/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0400 - loss: 3.1873     
Epoch 11/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0400 - loss: 3.1774     
Epoch 12/500
25/2

In [32]:
model.evaluate(x_norm,y_new, batch_size=1)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8800 - loss: 1.3087  


[1.308730959892273, 0.8799999952316284]

In [33]:
from numpy import argmax

new = 'M'
new = char_to_int[new]
new = np.reshape(new,(1,1,1))
new = new/25
pred = model.predict(new, verbose=False)
pred = np.argmax(pred)
int_to_char[pred]

'N'

### seq_length = 3

In [34]:
### Prepare the dataset
seq_length = 3
x = []
y = []

for i in range(len(alphabets)-seq_length):
    seq_in = alphabets [i:i+seq_length]
    seq_out = alphabets[i+seq_length]
    print(seq_in,'--->',seq_out)
    x.append([char_to_int[char] for char in seq_in])
    y+= [char_to_int[seq_out]]

ABC ---> D
BCD ---> E
CDE ---> F
DEF ---> G
EFG ---> H
FGH ---> I
GHI ---> J
HIJ ---> K
IJK ---> L
JKL ---> M
KLM ---> N
LMN ---> O
MNO ---> P
NOP ---> Q
OPQ ---> R
PQR ---> S
QRS ---> T
RST ---> U
STU ---> V
TUV ---> W
UVW ---> X
VWX ---> Y
WXY ---> Z


In [35]:
x=np.reshape(x,(23,seq_length,1))

In [36]:
x_norm = x/25

In [37]:
y_new = to_categorical(y)

In [38]:
model = Sequential()
model.add(Input((3,1)))
model.add(Dense(25,activation='relu'))
model.add(SimpleRNN(32))
model.add(Dense(26,activation='softmax'))
model.summary()


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 3, 25)          │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ (None, 32)             │         1,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 26)             │           858 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,764 (10.80 KB)

 Trainable params: 2,764 (10.80 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_norm,y_new,epochs=1000,batch_size=1)

Epoch 1/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0000e+00 - loss: 3.2983   
Epoch 2/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 3.2382 
Epoch 3/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0435 - loss: 3.2156     
Epoch 4/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0435 - loss: 3.1920     
Epoch 5/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 3.1653 
Epoch 6/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0435 - loss: 3.1382     
Epoch 7/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0435 - loss: 3.1117     
Epoch 8/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0435 - loss: 3.0826     
Epoch 9/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0435 - loss: 3.0525     
Epoch 10/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0435 - loss: 3.0167     
Epoch 11/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.1304 - loss: 2.9686 

In [40]:
model.evaluate(x_norm,y_new, batch_size=1)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9565 - loss: 0.1325  


[0.1325453221797943, 0.95652174949646]

In [41]:
from numpy import argmax

new_c = 'MNO'
new = [char_to_int[char] for char in new_c] 
new = np.reshape(new,(1,3,1))
new = new/25
pred = model.predict(new, verbose=False)
pred = np.argmax(pred)
# out = int_to_char[pred]
print(new_c,'--->',int_to_char[pred])

MNO ---> P


In [43]:
### Prepare the dataset To do assignment with 4
# seq_length = 3
# x = []
# y = []
#
# for i in range(len(alphabets)-seq_length):
#     seq_in = alphabets [i:i+seq_length]
#     seq_out = alphabets[i+seq_length]
#     print(seq_in,'--->',seq_out)
#     x.append([char_to_int[char] for char in seq_in])
#     y+= [char_to_int[seq_out]]